version: "3.3"
services:
  rabbit-mq:
    image: rabbitmq:3.7.5-alpine
    ports:
      - "5672:5672"
  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  db:
    image: mongo:3.6.5-jessie
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbit-mq
    ports:
      - "5000:5000"
    command: >
      /bin/bash -c "
        cd src && python __main__.py
      "
    restart: on-failure
    volumes:
      - ./:/app
    links:
      - rabbit-mq
      - redis
      - db
    depends_on:
      - rabbit-mq
      - redis
      - db

volumes:
  redis-data:
  mongodb-data:
