version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    command: > /bin/sh -c "
      python __main__.py
    "
  db:
    image: mongo:3.6
    volumes:
      - mongodb-data:/data/db
volumes:
  monogdb-data:
