version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: >
      /bin/sh -c "
        python src/__main__.py
      "
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:3.6
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
