version: "3.3"
services:

  rabbit-mq:
    image: rabbitmq:3.7.6-management-alpine
    ports:
      - "5672:5672"
      - "8080:15672"
    hostname: my-rabbit # https://hub.docker.com/_/rabbitmq/
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: mongo:3.6.5-jessie
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  bar:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbit-mq
    command: >
      /bin/bash -c "
        cd src/bar/lib/bar && python bar.py
      "
    restart: on-failure
    volumes:
      - type: bind
        source: "$PWD"
        target: /app
    links:
      - rabbit-mq
    depends_on:
      - rabbit-mq

  foo:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbit-mq
      MONGO_HOST: db
      MONGO_PORT: 27017
    ports:
      - "5000:5000"
    command: >
      /bin/bash -c "
        cd src/foo/lib/foo && python foo.py
      "
    restart: on-failure
    volumes:
      - type: bind
        source: "$PWD"
        target: /app
    links:
      - rabbit-mq
      - redis
      - db
    depends_on:
      - rabbit-mq
      - redis
      - db

volumes:
  rabbitmq-data:
  redis-data:
  mongodb-data:
